const ARXIV_CATEGORIES: Record<string, string> = {
  "cs.AI": "AI",
  "cs.CL": "NLP",
  "cs.CV": "Computer Vision",
  "cs.LG": "Machine Learning",
  "cs.NE": "Neural & Evolutionary",
  "cs.IR": "Information Retrieval",
  "cs.RO": "Robotics",
  "cs.SE": "Software Engineering",
  "cs.CR": "Cryptography",
  "cs.DS": "Data Structures",
  "cs.DB": "Databases",
  "cs.DC": "Distributed Computing",
  "cs.GT": "Game Theory",
  "cs.HC": "HCI",
  "cs.IT": "Information Theory",
  "cs.MA": "Multiagent Systems",
  "cs.MM": "Multimedia",
  "cs.NI": "Networking",
  "cs.OS": "Operating Systems",
  "cs.PF": "Performance",
  "cs.PL": "Programming Languages",
  "cs.SI": "Social Networks",
  "cs.SY": "Systems & Control",
  "cs.CY": "Computers & Society",
  "cs.AR": "Hardware Architecture",
  "cs.CC": "Computational Complexity",
  "cs.CE": "Computational Engineering",
  "cs.CG": "Computational Geometry",
  "cs.DL": "Digital Libraries",
  "cs.DM": "Discrete Mathematics",
  "cs.ET": "Emerging Technologies",
  "cs.FL": "Formal Languages",
  "cs.GL": "General Literature",
  "cs.GR": "Graphics",
  "cs.LO": "Logic",
  "cs.MS": "Mathematical Software",
  "cs.NA": "Numerical Analysis",
  "cs.SC": "Symbolic Computation",
  "cs.SD": "Sound",
  "stat.ML": "Machine Learning",
  "stat.AP": "Statistics",
  "stat.CO": "Computation",
  "stat.ME": "Methodology",
  "stat.TH": "Statistics Theory",
  "math.OC": "Optimization",
  "math.ST": "Statistics",
  "math.NA": "Numerical Analysis",
  "math.PR": "Probability",
  "eess.AS": "Audio & Speech",
  "eess.IV": "Image & Video",
  "eess.SP": "Signal Processing",
  "eess.SY": "Systems & Control",
  "q-bio.NC": "Neuroscience",
  "q-bio.QM": "Quantitative Methods",
  "q-bio.GN": "Genomics",
  "physics.comp-ph": "Computational Physics",
  "physics.data-an": "Data Analysis",
  "quant-ph": "Quantum Physics",
  "cond-mat": "Condensed Matter",
  "hep-th": "High Energy Physics",
  "astro-ph": "Astrophysics",
};

export function humanCategory(cat: string): string {
  return ARXIV_CATEGORIES[cat] || cat;
}
